CREATE TABLE IF NOT EXISTS login(
	id SERIAL PRIMARY KEY,
	hash TEXT ,
	email TEXT
);

CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	name TEXT ,
	email TEXT,
  picture TEXT
);

CREATE TABLE IF NOT EXISTS english (
	id SERIAL PRIMARY KEY,
	title TEXT ,
	content TEXT
);

CREATE TABLE IF NOT EXISTS spanish (
	id SERIAL PRIMARY KEY,
	title TEXT ,
	content TEXT
);